### ISSUE TITLE
About how to generate realistic face

### ISSUE THREAD

**Issue by ava-YangL** [JannerM/face-intrinsics#1]
Hi, i find the face generated by original BFM model is more realistic ,i am wondering if you have any idea about this issue? 
Thanks.

**Comment by jannerm** [comment]
This is probably because of the shading setup (since the meshes and textures are the same). If you take out the `--background` flag in [run.sh](https://github.com/JannerM/face-intrinsics/blob/master/run.sh#L6), and then put a breakpoint in [render.py](https://github.com/JannerM/face-intrinsics/blob/master/render.py#L62) (something like `pdb.set_trace()`), you'll see the GUI for Blender:

![image](https://user-images.githubusercontent.com/10070626/43063043-16d822e6-8e9e-11e8-83a0-d46ffb0aba3d.png)

From here you can play around with shading options and different lighting. For example, here's an image with the current parameters:

![original](https://user-images.githubusercontent.com/10070626/43063158-763636a6-8e9e-11e8-870e-551eeebf82eb.png)

here is one with increased specularity (probably not what you want)

![specular_0 5](https://user-images.githubusercontent.com/10070626/43063183-82c70f9e-8e9e-11e8-92aa-94342b5ed5e3.png)

and here is one with hemi lighting instead of point lighting. (Maybe a tiny bit more similar to the Matlab rendering?)

![hemi](https://user-images.githubusercontent.com/10070626/43063223-9f5ca75e-8e9e-11e8-9330-6a8401825daa.png)

**Comment by ava-YangL** [comment]
Thank you for the kind reply,and here are two images from this project / the original BFM model,maybe the albedo generated by the original BFM model is more realistic?
Here is the albedo i got from this project：
![_20180726151024](https://user-images.githubusercontent.com/33688725/43247414-360770ea-90e7-11e8-9849-0b41202984e3.png)
Here is the albedo i got from the original BFM model in matlab:
![_20180726151013](https://user-images.githubusercontent.com/33688725/43247413-35a2b5ce-90e7-11e8-990c-13a37078b08d.png)
